// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	NjApp             *njApp
	NjAppJob          *njAppJob
	NjAppJobParams    *njAppJobParams
	NjAppJobResult    *njAppJobResult
	NjAppJobSubResult *njAppJobSubResult
	NjNamespace       *njNamespace
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	NjApp = &Q.NjApp
	NjAppJob = &Q.NjAppJob
	NjAppJobParams = &Q.NjAppJobParams
	NjAppJobResult = &Q.NjAppJobResult
	NjAppJobSubResult = &Q.NjAppJobSubResult
	NjNamespace = &Q.NjNamespace
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		NjApp:             newNjApp(db, opts...),
		NjAppJob:          newNjAppJob(db, opts...),
		NjAppJobParams:    newNjAppJobParams(db, opts...),
		NjAppJobResult:    newNjAppJobResult(db, opts...),
		NjAppJobSubResult: newNjAppJobSubResult(db, opts...),
		NjNamespace:       newNjNamespace(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	NjApp             njApp
	NjAppJob          njAppJob
	NjAppJobParams    njAppJobParams
	NjAppJobResult    njAppJobResult
	NjAppJobSubResult njAppJobSubResult
	NjNamespace       njNamespace
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		NjApp:             q.NjApp.clone(db),
		NjAppJob:          q.NjAppJob.clone(db),
		NjAppJobParams:    q.NjAppJobParams.clone(db),
		NjAppJobResult:    q.NjAppJobResult.clone(db),
		NjAppJobSubResult: q.NjAppJobSubResult.clone(db),
		NjNamespace:       q.NjNamespace.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		NjApp:             q.NjApp.replaceDB(db),
		NjAppJob:          q.NjAppJob.replaceDB(db),
		NjAppJobParams:    q.NjAppJobParams.replaceDB(db),
		NjAppJobResult:    q.NjAppJobResult.replaceDB(db),
		NjAppJobSubResult: q.NjAppJobSubResult.replaceDB(db),
		NjNamespace:       q.NjNamespace.replaceDB(db),
	}
}

type queryCtx struct {
	NjApp             INjAppDo
	NjAppJob          INjAppJobDo
	NjAppJobParams    INjAppJobParamsDo
	NjAppJobResult    INjAppJobResultDo
	NjAppJobSubResult INjAppJobSubResultDo
	NjNamespace       INjNamespaceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		NjApp:             q.NjApp.WithContext(ctx),
		NjAppJob:          q.NjAppJob.WithContext(ctx),
		NjAppJobParams:    q.NjAppJobParams.WithContext(ctx),
		NjAppJobResult:    q.NjAppJobResult.WithContext(ctx),
		NjAppJobSubResult: q.NjAppJobSubResult.WithContext(ctx),
		NjNamespace:       q.NjNamespace.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
