// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"natsjob/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNjApp(db *gorm.DB, opts ...gen.DOOption) njApp {
	_njApp := njApp{}

	_njApp.njAppDo.UseDB(db, opts...)
	_njApp.njAppDo.UseModel(&model.NjApp{})

	tableName := _njApp.njAppDo.TableName()
	_njApp.ALL = field.NewAsterisk(tableName)
	_njApp.ID = field.NewInt64(tableName, "id")
	_njApp.Name = field.NewString(tableName, "name")
	_njApp.Description = field.NewString(tableName, "description")
	_njApp.NamespaceId = field.NewInt64(tableName, "namespace_id")
	_njApp.Deleted = field.NewInt8(tableName, "deleted")
	_njApp.CreatedAt = field.NewTime(tableName, "created_at")
	_njApp.UpdatedAt = field.NewTime(tableName, "updated_at")

	_njApp.fillFieldMap()

	return _njApp
}

type njApp struct {
	njAppDo njAppDo

	ALL         field.Asterisk
	ID          field.Int64  // 'id'
	Name        field.String // '应用名称'
	Description field.String // '命名空间描述'
	NamespaceId field.Int64  // '命名空间ID'
	Deleted     field.Int8   // '删除标记'
	CreatedAt   field.Time   // '创建时间'
	UpdatedAt   field.Time   // '更新时间'

	fieldMap map[string]field.Expr
}

func (n njApp) Table(newTableName string) *njApp {
	n.njAppDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n njApp) As(alias string) *njApp {
	n.njAppDo.DO = *(n.njAppDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *njApp) updateTableName(table string) *njApp {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.Name = field.NewString(table, "name")
	n.Description = field.NewString(table, "description")
	n.NamespaceId = field.NewInt64(table, "namespace_id")
	n.Deleted = field.NewInt8(table, "deleted")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *njApp) WithContext(ctx context.Context) INjAppDo { return n.njAppDo.WithContext(ctx) }

func (n njApp) TableName() string { return n.njAppDo.TableName() }

func (n njApp) Alias() string { return n.njAppDo.Alias() }

func (n njApp) Columns(cols ...field.Expr) gen.Columns { return n.njAppDo.Columns(cols...) }

func (n *njApp) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *njApp) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 7)
	n.fieldMap["id"] = n.ID
	n.fieldMap["name"] = n.Name
	n.fieldMap["description"] = n.Description
	n.fieldMap["namespace_id"] = n.NamespaceId
	n.fieldMap["deleted"] = n.Deleted
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n njApp) clone(db *gorm.DB) njApp {
	n.njAppDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n njApp) replaceDB(db *gorm.DB) njApp {
	n.njAppDo.ReplaceDB(db)
	return n
}

type njAppDo struct{ gen.DO }

type INjAppDo interface {
	gen.SubQuery
	Debug() INjAppDo
	WithContext(ctx context.Context) INjAppDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INjAppDo
	WriteDB() INjAppDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INjAppDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INjAppDo
	Not(conds ...gen.Condition) INjAppDo
	Or(conds ...gen.Condition) INjAppDo
	Select(conds ...field.Expr) INjAppDo
	Where(conds ...gen.Condition) INjAppDo
	Order(conds ...field.Expr) INjAppDo
	Distinct(cols ...field.Expr) INjAppDo
	Omit(cols ...field.Expr) INjAppDo
	Join(table schema.Tabler, on ...field.Expr) INjAppDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INjAppDo
	RightJoin(table schema.Tabler, on ...field.Expr) INjAppDo
	Group(cols ...field.Expr) INjAppDo
	Having(conds ...gen.Condition) INjAppDo
	Limit(limit int) INjAppDo
	Offset(offset int) INjAppDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INjAppDo
	Unscoped() INjAppDo
	Create(values ...*model.NjApp) error
	CreateInBatches(values []*model.NjApp, batchSize int) error
	Save(values ...*model.NjApp) error
	First() (*model.NjApp, error)
	Take() (*model.NjApp, error)
	Last() (*model.NjApp, error)
	Find() ([]*model.NjApp, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjApp, err error)
	FindInBatches(result *[]*model.NjApp, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NjApp) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INjAppDo
	Assign(attrs ...field.AssignExpr) INjAppDo
	Joins(fields ...field.RelationField) INjAppDo
	Preload(fields ...field.RelationField) INjAppDo
	FirstOrInit() (*model.NjApp, error)
	FirstOrCreate() (*model.NjApp, error)
	FindByPage(offset int, limit int) (result []*model.NjApp, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INjAppDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n njAppDo) Debug() INjAppDo {
	return n.withDO(n.DO.Debug())
}

func (n njAppDo) WithContext(ctx context.Context) INjAppDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n njAppDo) ReadDB() INjAppDo {
	return n.Clauses(dbresolver.Read)
}

func (n njAppDo) WriteDB() INjAppDo {
	return n.Clauses(dbresolver.Write)
}

func (n njAppDo) Session(config *gorm.Session) INjAppDo {
	return n.withDO(n.DO.Session(config))
}

func (n njAppDo) Clauses(conds ...clause.Expression) INjAppDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n njAppDo) Returning(value interface{}, columns ...string) INjAppDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n njAppDo) Not(conds ...gen.Condition) INjAppDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n njAppDo) Or(conds ...gen.Condition) INjAppDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n njAppDo) Select(conds ...field.Expr) INjAppDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n njAppDo) Where(conds ...gen.Condition) INjAppDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n njAppDo) Order(conds ...field.Expr) INjAppDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n njAppDo) Distinct(cols ...field.Expr) INjAppDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n njAppDo) Omit(cols ...field.Expr) INjAppDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n njAppDo) Join(table schema.Tabler, on ...field.Expr) INjAppDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n njAppDo) LeftJoin(table schema.Tabler, on ...field.Expr) INjAppDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n njAppDo) RightJoin(table schema.Tabler, on ...field.Expr) INjAppDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n njAppDo) Group(cols ...field.Expr) INjAppDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n njAppDo) Having(conds ...gen.Condition) INjAppDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n njAppDo) Limit(limit int) INjAppDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n njAppDo) Offset(offset int) INjAppDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n njAppDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INjAppDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n njAppDo) Unscoped() INjAppDo {
	return n.withDO(n.DO.Unscoped())
}

func (n njAppDo) Create(values ...*model.NjApp) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n njAppDo) CreateInBatches(values []*model.NjApp, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n njAppDo) Save(values ...*model.NjApp) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n njAppDo) First() (*model.NjApp, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjApp), nil
	}
}

func (n njAppDo) Take() (*model.NjApp, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjApp), nil
	}
}

func (n njAppDo) Last() (*model.NjApp, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjApp), nil
	}
}

func (n njAppDo) Find() ([]*model.NjApp, error) {
	result, err := n.DO.Find()
	return result.([]*model.NjApp), err
}

func (n njAppDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjApp, err error) {
	buf := make([]*model.NjApp, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n njAppDo) FindInBatches(result *[]*model.NjApp, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n njAppDo) Attrs(attrs ...field.AssignExpr) INjAppDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n njAppDo) Assign(attrs ...field.AssignExpr) INjAppDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n njAppDo) Joins(fields ...field.RelationField) INjAppDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n njAppDo) Preload(fields ...field.RelationField) INjAppDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n njAppDo) FirstOrInit() (*model.NjApp, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjApp), nil
	}
}

func (n njAppDo) FirstOrCreate() (*model.NjApp, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjApp), nil
	}
}

func (n njAppDo) FindByPage(offset int, limit int) (result []*model.NjApp, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n njAppDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n njAppDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n njAppDo) Delete(models ...*model.NjApp) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *njAppDo) withDO(do gen.Dao) *njAppDo {
	n.DO = *do.(*gen.DO)
	return n
}
