// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"natsjob/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNjAppJobParams(db *gorm.DB, opts ...gen.DOOption) njAppJobParams {
	_njAppJobParams := njAppJobParams{}

	_njAppJobParams.njAppJobParamsDo.UseDB(db, opts...)
	_njAppJobParams.njAppJobParamsDo.UseModel(&model.NjAppJobParams{})

	tableName := _njAppJobParams.njAppJobParamsDo.TableName()
	_njAppJobParams.ALL = field.NewAsterisk(tableName)
	_njAppJobParams.ID = field.NewInt64(tableName, "id")
	_njAppJobParams.Name = field.NewString(tableName, "name")
	_njAppJobParams.ClientID = field.NewString(tableName, "client_id")
	_njAppJobParams.SceneID = field.NewString(tableName, "scene_id")
	_njAppJobParams.SceneName = field.NewString(tableName, "scene_name")
	_njAppJobParams.Description = field.NewString(tableName, "description")
	_njAppJobParams.Args = field.NewString(tableName, "args")
	_njAppJobParams.Priority = field.NewInt32(tableName, "priority")
	_njAppJobParams.Weight = field.NewInt32(tableName, "weight")
	_njAppJobParams.JobId = field.NewInt64(tableName, "job_id")
	_njAppJobParams.Deleted = field.NewInt32(tableName, "deleted")
	_njAppJobParams.CreatedAt = field.NewTime(tableName, "created_at")
	_njAppJobParams.UpdatedAt = field.NewTime(tableName, "updated_at")

	_njAppJobParams.fillFieldMap()

	return _njAppJobParams
}

type njAppJobParams struct {
	njAppJobParamsDo njAppJobParamsDo

	ALL         field.Asterisk
	ID          field.Int64  // 'id'
	Name        field.String // '名称'
	ClientID    field.String // '客户端id'
	SceneID     field.String // '场景id'
	SceneName   field.String // '场景名称'
	Description field.String // '描述'
	Args        field.String // '参数'
	Priority    field.Int32  // '优先级'
	Weight      field.Int32  // '权重'
	JobId       field.Int64  // '作业id'
	Deleted     field.Int32  // '删除标记'
	CreatedAt   field.Time   // '创建时间'
	UpdatedAt   field.Time   // '更新时间'

	fieldMap map[string]field.Expr
}

func (n njAppJobParams) Table(newTableName string) *njAppJobParams {
	n.njAppJobParamsDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n njAppJobParams) As(alias string) *njAppJobParams {
	n.njAppJobParamsDo.DO = *(n.njAppJobParamsDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *njAppJobParams) updateTableName(table string) *njAppJobParams {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.Name = field.NewString(table, "name")
	n.ClientID = field.NewString(table, "client_id")
	n.SceneID = field.NewString(table, "scene_id")
	n.SceneName = field.NewString(table, "scene_name")
	n.Description = field.NewString(table, "description")
	n.Args = field.NewString(table, "args")
	n.Priority = field.NewInt32(table, "priority")
	n.Weight = field.NewInt32(table, "weight")
	n.JobId = field.NewInt64(table, "job_id")
	n.Deleted = field.NewInt32(table, "deleted")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *njAppJobParams) WithContext(ctx context.Context) INjAppJobParamsDo {
	return n.njAppJobParamsDo.WithContext(ctx)
}

func (n njAppJobParams) TableName() string { return n.njAppJobParamsDo.TableName() }

func (n njAppJobParams) Alias() string { return n.njAppJobParamsDo.Alias() }

func (n njAppJobParams) Columns(cols ...field.Expr) gen.Columns {
	return n.njAppJobParamsDo.Columns(cols...)
}

func (n *njAppJobParams) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *njAppJobParams) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 13)
	n.fieldMap["id"] = n.ID
	n.fieldMap["name"] = n.Name
	n.fieldMap["client_id"] = n.ClientID
	n.fieldMap["scene_id"] = n.SceneID
	n.fieldMap["scene_name"] = n.SceneName
	n.fieldMap["description"] = n.Description
	n.fieldMap["args"] = n.Args
	n.fieldMap["priority"] = n.Priority
	n.fieldMap["weight"] = n.Weight
	n.fieldMap["job_id"] = n.JobId
	n.fieldMap["deleted"] = n.Deleted
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n njAppJobParams) clone(db *gorm.DB) njAppJobParams {
	n.njAppJobParamsDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n njAppJobParams) replaceDB(db *gorm.DB) njAppJobParams {
	n.njAppJobParamsDo.ReplaceDB(db)
	return n
}

type njAppJobParamsDo struct{ gen.DO }

type INjAppJobParamsDo interface {
	gen.SubQuery
	Debug() INjAppJobParamsDo
	WithContext(ctx context.Context) INjAppJobParamsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INjAppJobParamsDo
	WriteDB() INjAppJobParamsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INjAppJobParamsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INjAppJobParamsDo
	Not(conds ...gen.Condition) INjAppJobParamsDo
	Or(conds ...gen.Condition) INjAppJobParamsDo
	Select(conds ...field.Expr) INjAppJobParamsDo
	Where(conds ...gen.Condition) INjAppJobParamsDo
	Order(conds ...field.Expr) INjAppJobParamsDo
	Distinct(cols ...field.Expr) INjAppJobParamsDo
	Omit(cols ...field.Expr) INjAppJobParamsDo
	Join(table schema.Tabler, on ...field.Expr) INjAppJobParamsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INjAppJobParamsDo
	RightJoin(table schema.Tabler, on ...field.Expr) INjAppJobParamsDo
	Group(cols ...field.Expr) INjAppJobParamsDo
	Having(conds ...gen.Condition) INjAppJobParamsDo
	Limit(limit int) INjAppJobParamsDo
	Offset(offset int) INjAppJobParamsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INjAppJobParamsDo
	Unscoped() INjAppJobParamsDo
	Create(values ...*model.NjAppJobParams) error
	CreateInBatches(values []*model.NjAppJobParams, batchSize int) error
	Save(values ...*model.NjAppJobParams) error
	First() (*model.NjAppJobParams, error)
	Take() (*model.NjAppJobParams, error)
	Last() (*model.NjAppJobParams, error)
	Find() ([]*model.NjAppJobParams, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjAppJobParams, err error)
	FindInBatches(result *[]*model.NjAppJobParams, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NjAppJobParams) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INjAppJobParamsDo
	Assign(attrs ...field.AssignExpr) INjAppJobParamsDo
	Joins(fields ...field.RelationField) INjAppJobParamsDo
	Preload(fields ...field.RelationField) INjAppJobParamsDo
	FirstOrInit() (*model.NjAppJobParams, error)
	FirstOrCreate() (*model.NjAppJobParams, error)
	FindByPage(offset int, limit int) (result []*model.NjAppJobParams, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INjAppJobParamsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n njAppJobParamsDo) Debug() INjAppJobParamsDo {
	return n.withDO(n.DO.Debug())
}

func (n njAppJobParamsDo) WithContext(ctx context.Context) INjAppJobParamsDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n njAppJobParamsDo) ReadDB() INjAppJobParamsDo {
	return n.Clauses(dbresolver.Read)
}

func (n njAppJobParamsDo) WriteDB() INjAppJobParamsDo {
	return n.Clauses(dbresolver.Write)
}

func (n njAppJobParamsDo) Session(config *gorm.Session) INjAppJobParamsDo {
	return n.withDO(n.DO.Session(config))
}

func (n njAppJobParamsDo) Clauses(conds ...clause.Expression) INjAppJobParamsDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n njAppJobParamsDo) Returning(value interface{}, columns ...string) INjAppJobParamsDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n njAppJobParamsDo) Not(conds ...gen.Condition) INjAppJobParamsDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n njAppJobParamsDo) Or(conds ...gen.Condition) INjAppJobParamsDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n njAppJobParamsDo) Select(conds ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n njAppJobParamsDo) Where(conds ...gen.Condition) INjAppJobParamsDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n njAppJobParamsDo) Order(conds ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n njAppJobParamsDo) Distinct(cols ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n njAppJobParamsDo) Omit(cols ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n njAppJobParamsDo) Join(table schema.Tabler, on ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n njAppJobParamsDo) LeftJoin(table schema.Tabler, on ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n njAppJobParamsDo) RightJoin(table schema.Tabler, on ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n njAppJobParamsDo) Group(cols ...field.Expr) INjAppJobParamsDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n njAppJobParamsDo) Having(conds ...gen.Condition) INjAppJobParamsDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n njAppJobParamsDo) Limit(limit int) INjAppJobParamsDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n njAppJobParamsDo) Offset(offset int) INjAppJobParamsDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n njAppJobParamsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INjAppJobParamsDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n njAppJobParamsDo) Unscoped() INjAppJobParamsDo {
	return n.withDO(n.DO.Unscoped())
}

func (n njAppJobParamsDo) Create(values ...*model.NjAppJobParams) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n njAppJobParamsDo) CreateInBatches(values []*model.NjAppJobParams, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n njAppJobParamsDo) Save(values ...*model.NjAppJobParams) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n njAppJobParamsDo) First() (*model.NjAppJobParams, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJobParams), nil
	}
}

func (n njAppJobParamsDo) Take() (*model.NjAppJobParams, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJobParams), nil
	}
}

func (n njAppJobParamsDo) Last() (*model.NjAppJobParams, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJobParams), nil
	}
}

func (n njAppJobParamsDo) Find() ([]*model.NjAppJobParams, error) {
	result, err := n.DO.Find()
	return result.([]*model.NjAppJobParams), err
}

func (n njAppJobParamsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjAppJobParams, err error) {
	buf := make([]*model.NjAppJobParams, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n njAppJobParamsDo) FindInBatches(result *[]*model.NjAppJobParams, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n njAppJobParamsDo) Attrs(attrs ...field.AssignExpr) INjAppJobParamsDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n njAppJobParamsDo) Assign(attrs ...field.AssignExpr) INjAppJobParamsDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n njAppJobParamsDo) Joins(fields ...field.RelationField) INjAppJobParamsDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n njAppJobParamsDo) Preload(fields ...field.RelationField) INjAppJobParamsDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n njAppJobParamsDo) FirstOrInit() (*model.NjAppJobParams, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJobParams), nil
	}
}

func (n njAppJobParamsDo) FirstOrCreate() (*model.NjAppJobParams, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJobParams), nil
	}
}

func (n njAppJobParamsDo) FindByPage(offset int, limit int) (result []*model.NjAppJobParams, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n njAppJobParamsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n njAppJobParamsDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n njAppJobParamsDo) Delete(models ...*model.NjAppJobParams) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *njAppJobParamsDo) withDO(do gen.Dao) *njAppJobParamsDo {
	n.DO = *do.(*gen.DO)
	return n
}
