// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"natsjob/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNjAppJob(db *gorm.DB, opts ...gen.DOOption) njAppJob {
	_njAppJob := njAppJob{}

	_njAppJob.njAppJobDo.UseDB(db, opts...)
	_njAppJob.njAppJobDo.UseModel(&model.NjAppJob{})

	tableName := _njAppJob.njAppJobDo.TableName()
	_njAppJob.ALL = field.NewAsterisk(tableName)
	_njAppJob.ID = field.NewInt64(tableName, "id")
	_njAppJob.Name = field.NewString(tableName, "name")
	_njAppJob.Cron = field.NewString(tableName, "cron")
	_njAppJob.Category = field.NewString(tableName, "category")
	_njAppJob.Model = field.NewString(tableName, "model")
	_njAppJob.Status = field.NewInt8(tableName, "status")
	_njAppJob.Condition = field.NewString(tableName, "condition")
	_njAppJob.MaxWorkers = field.NewInt32(tableName, "max_workers")
	_njAppJob.TimeoutSeconds = field.NewInt32(tableName, "timeout_seconds")
	_njAppJob.Description = field.NewString(tableName, "description")
	_njAppJob.Reason = field.NewString(tableName, "reason")
	_njAppJob.Args = field.NewString(tableName, "args")
	_njAppJob.NamespaceId = field.NewInt64(tableName, "namespace_id")
	_njAppJob.AppId = field.NewInt64(tableName, "app_id")
	_njAppJob.StartAt = field.NewTime(tableName, "start_at")
	_njAppJob.EndAt = field.NewTime(tableName, "end_at")
	_njAppJob.Deleted = field.NewInt8(tableName, "deleted")
	_njAppJob.CreatedAt = field.NewTime(tableName, "created_at")
	_njAppJob.UpdatedAt = field.NewTime(tableName, "updated_at")

	_njAppJob.fillFieldMap()

	return _njAppJob
}

type njAppJob struct {
	njAppJobDo njAppJobDo

	ALL            field.Asterisk
	ID             field.Int64  // 'id'
	Name           field.String // '应用作业名称'
	Cron           field.String // 'cron表达式'
	Category       field.String // '策略'
	Model          field.String // '模式'
	Status         field.Int8   // '状态
	Condition      field.String // '条件'
	MaxWorkers     field.Int32  // '最大工作节点数'
	TimeoutSeconds field.Int32  // '超时秒数'
	Description    field.String // '描述'
	Reason         field.String // '原因'
	Args           field.String // '参数'
	NamespaceId    field.Int64  // '命名空间ID'
	AppId          field.Int64  // '应用ID'
	StartAt        field.Time   // '开始时间'
	EndAt          field.Time   // '结束时间'
	Deleted        field.Int8   // '删除标记'
	CreatedAt      field.Time   // '创建时间'
	UpdatedAt      field.Time   // '更新时间'

	fieldMap map[string]field.Expr
}

func (n njAppJob) Table(newTableName string) *njAppJob {
	n.njAppJobDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n njAppJob) As(alias string) *njAppJob {
	n.njAppJobDo.DO = *(n.njAppJobDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *njAppJob) updateTableName(table string) *njAppJob {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.Name = field.NewString(table, "name")
	n.Cron = field.NewString(table, "cron")
	n.Category = field.NewString(table, "category")
	n.Model = field.NewString(table, "model")
	n.Status = field.NewInt8(table, "status")
	n.Condition = field.NewString(table, "condition")
	n.MaxWorkers = field.NewInt32(table, "max_workers")
	n.TimeoutSeconds = field.NewInt32(table, "timeout_seconds")
	n.Description = field.NewString(table, "description")
	n.Reason = field.NewString(table, "reason")
	n.Args = field.NewString(table, "args")
	n.NamespaceId = field.NewInt64(table, "namespace_id")
	n.AppId = field.NewInt64(table, "app_id")
	n.StartAt = field.NewTime(table, "start_at")
	n.EndAt = field.NewTime(table, "end_at")
	n.Deleted = field.NewInt8(table, "deleted")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *njAppJob) WithContext(ctx context.Context) INjAppJobDo { return n.njAppJobDo.WithContext(ctx) }

func (n njAppJob) TableName() string { return n.njAppJobDo.TableName() }

func (n njAppJob) Alias() string { return n.njAppJobDo.Alias() }

func (n njAppJob) Columns(cols ...field.Expr) gen.Columns { return n.njAppJobDo.Columns(cols...) }

func (n *njAppJob) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *njAppJob) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 19)
	n.fieldMap["id"] = n.ID
	n.fieldMap["name"] = n.Name
	n.fieldMap["cron"] = n.Cron
	n.fieldMap["category"] = n.Category
	n.fieldMap["model"] = n.Model
	n.fieldMap["status"] = n.Status
	n.fieldMap["condition"] = n.Condition
	n.fieldMap["max_workers"] = n.MaxWorkers
	n.fieldMap["timeout_seconds"] = n.TimeoutSeconds
	n.fieldMap["description"] = n.Description
	n.fieldMap["reason"] = n.Reason
	n.fieldMap["args"] = n.Args
	n.fieldMap["namespace_id"] = n.NamespaceId
	n.fieldMap["app_id"] = n.AppId
	n.fieldMap["start_at"] = n.StartAt
	n.fieldMap["end_at"] = n.EndAt
	n.fieldMap["deleted"] = n.Deleted
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n njAppJob) clone(db *gorm.DB) njAppJob {
	n.njAppJobDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n njAppJob) replaceDB(db *gorm.DB) njAppJob {
	n.njAppJobDo.ReplaceDB(db)
	return n
}

type njAppJobDo struct{ gen.DO }

type INjAppJobDo interface {
	gen.SubQuery
	Debug() INjAppJobDo
	WithContext(ctx context.Context) INjAppJobDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INjAppJobDo
	WriteDB() INjAppJobDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INjAppJobDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INjAppJobDo
	Not(conds ...gen.Condition) INjAppJobDo
	Or(conds ...gen.Condition) INjAppJobDo
	Select(conds ...field.Expr) INjAppJobDo
	Where(conds ...gen.Condition) INjAppJobDo
	Order(conds ...field.Expr) INjAppJobDo
	Distinct(cols ...field.Expr) INjAppJobDo
	Omit(cols ...field.Expr) INjAppJobDo
	Join(table schema.Tabler, on ...field.Expr) INjAppJobDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INjAppJobDo
	RightJoin(table schema.Tabler, on ...field.Expr) INjAppJobDo
	Group(cols ...field.Expr) INjAppJobDo
	Having(conds ...gen.Condition) INjAppJobDo
	Limit(limit int) INjAppJobDo
	Offset(offset int) INjAppJobDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INjAppJobDo
	Unscoped() INjAppJobDo
	Create(values ...*model.NjAppJob) error
	CreateInBatches(values []*model.NjAppJob, batchSize int) error
	Save(values ...*model.NjAppJob) error
	First() (*model.NjAppJob, error)
	Take() (*model.NjAppJob, error)
	Last() (*model.NjAppJob, error)
	Find() ([]*model.NjAppJob, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjAppJob, err error)
	FindInBatches(result *[]*model.NjAppJob, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NjAppJob) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INjAppJobDo
	Assign(attrs ...field.AssignExpr) INjAppJobDo
	Joins(fields ...field.RelationField) INjAppJobDo
	Preload(fields ...field.RelationField) INjAppJobDo
	FirstOrInit() (*model.NjAppJob, error)
	FirstOrCreate() (*model.NjAppJob, error)
	FindByPage(offset int, limit int) (result []*model.NjAppJob, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INjAppJobDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n njAppJobDo) Debug() INjAppJobDo {
	return n.withDO(n.DO.Debug())
}

func (n njAppJobDo) WithContext(ctx context.Context) INjAppJobDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n njAppJobDo) ReadDB() INjAppJobDo {
	return n.Clauses(dbresolver.Read)
}

func (n njAppJobDo) WriteDB() INjAppJobDo {
	return n.Clauses(dbresolver.Write)
}

func (n njAppJobDo) Session(config *gorm.Session) INjAppJobDo {
	return n.withDO(n.DO.Session(config))
}

func (n njAppJobDo) Clauses(conds ...clause.Expression) INjAppJobDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n njAppJobDo) Returning(value interface{}, columns ...string) INjAppJobDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n njAppJobDo) Not(conds ...gen.Condition) INjAppJobDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n njAppJobDo) Or(conds ...gen.Condition) INjAppJobDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n njAppJobDo) Select(conds ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n njAppJobDo) Where(conds ...gen.Condition) INjAppJobDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n njAppJobDo) Order(conds ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n njAppJobDo) Distinct(cols ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n njAppJobDo) Omit(cols ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n njAppJobDo) Join(table schema.Tabler, on ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n njAppJobDo) LeftJoin(table schema.Tabler, on ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n njAppJobDo) RightJoin(table schema.Tabler, on ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n njAppJobDo) Group(cols ...field.Expr) INjAppJobDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n njAppJobDo) Having(conds ...gen.Condition) INjAppJobDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n njAppJobDo) Limit(limit int) INjAppJobDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n njAppJobDo) Offset(offset int) INjAppJobDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n njAppJobDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INjAppJobDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n njAppJobDo) Unscoped() INjAppJobDo {
	return n.withDO(n.DO.Unscoped())
}

func (n njAppJobDo) Create(values ...*model.NjAppJob) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n njAppJobDo) CreateInBatches(values []*model.NjAppJob, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n njAppJobDo) Save(values ...*model.NjAppJob) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n njAppJobDo) First() (*model.NjAppJob, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJob), nil
	}
}

func (n njAppJobDo) Take() (*model.NjAppJob, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJob), nil
	}
}

func (n njAppJobDo) Last() (*model.NjAppJob, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJob), nil
	}
}

func (n njAppJobDo) Find() ([]*model.NjAppJob, error) {
	result, err := n.DO.Find()
	return result.([]*model.NjAppJob), err
}

func (n njAppJobDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjAppJob, err error) {
	buf := make([]*model.NjAppJob, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n njAppJobDo) FindInBatches(result *[]*model.NjAppJob, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n njAppJobDo) Attrs(attrs ...field.AssignExpr) INjAppJobDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n njAppJobDo) Assign(attrs ...field.AssignExpr) INjAppJobDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n njAppJobDo) Joins(fields ...field.RelationField) INjAppJobDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n njAppJobDo) Preload(fields ...field.RelationField) INjAppJobDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n njAppJobDo) FirstOrInit() (*model.NjAppJob, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJob), nil
	}
}

func (n njAppJobDo) FirstOrCreate() (*model.NjAppJob, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjAppJob), nil
	}
}

func (n njAppJobDo) FindByPage(offset int, limit int) (result []*model.NjAppJob, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n njAppJobDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n njAppJobDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n njAppJobDo) Delete(models ...*model.NjAppJob) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *njAppJobDo) withDO(do gen.Dao) *njAppJobDo {
	n.DO = *do.(*gen.DO)
	return n
}
