// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"
	"natsjob/internal/model"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newNjNamespace(db *gorm.DB, opts ...gen.DOOption) njNamespace {
	_njNamespace := njNamespace{}

	_njNamespace.njNamespaceDo.UseDB(db, opts...)
	_njNamespace.njNamespaceDo.UseModel(&model.NjNamespace{})

	tableName := _njNamespace.njNamespaceDo.TableName()
	_njNamespace.ALL = field.NewAsterisk(tableName)
	_njNamespace.ID = field.NewInt64(tableName, "id")
	_njNamespace.Name = field.NewString(tableName, "name")
	_njNamespace.Description = field.NewString(tableName, "description")
	_njNamespace.Deleted = field.NewInt32(tableName, "deleted")
	_njNamespace.CreatedAt = field.NewTime(tableName, "created_at")
	_njNamespace.UpdatedAt = field.NewTime(tableName, "updated_at")

	_njNamespace.fillFieldMap()

	return _njNamespace
}

type njNamespace struct {
	njNamespaceDo njNamespaceDo

	ALL         field.Asterisk
	ID          field.Int64  // 'id'
	Name        field.String // '命名空间'
	Description field.String // '命名空间描述'
	Deleted     field.Int32  // '删除标记'
	CreatedAt   field.Time   // '创建时间'
	UpdatedAt   field.Time   // '更新时间'

	fieldMap map[string]field.Expr
}

func (n njNamespace) Table(newTableName string) *njNamespace {
	n.njNamespaceDo.UseTable(newTableName)
	return n.updateTableName(newTableName)
}

func (n njNamespace) As(alias string) *njNamespace {
	n.njNamespaceDo.DO = *(n.njNamespaceDo.As(alias).(*gen.DO))
	return n.updateTableName(alias)
}

func (n *njNamespace) updateTableName(table string) *njNamespace {
	n.ALL = field.NewAsterisk(table)
	n.ID = field.NewInt64(table, "id")
	n.Name = field.NewString(table, "name")
	n.Description = field.NewString(table, "description")
	n.Deleted = field.NewInt32(table, "deleted")
	n.CreatedAt = field.NewTime(table, "created_at")
	n.UpdatedAt = field.NewTime(table, "updated_at")

	n.fillFieldMap()

	return n
}

func (n *njNamespace) WithContext(ctx context.Context) INjNamespaceDo {
	return n.njNamespaceDo.WithContext(ctx)
}

func (n njNamespace) TableName() string { return n.njNamespaceDo.TableName() }

func (n njNamespace) Alias() string { return n.njNamespaceDo.Alias() }

func (n njNamespace) Columns(cols ...field.Expr) gen.Columns { return n.njNamespaceDo.Columns(cols...) }

func (n *njNamespace) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := n.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (n *njNamespace) fillFieldMap() {
	n.fieldMap = make(map[string]field.Expr, 6)
	n.fieldMap["id"] = n.ID
	n.fieldMap["name"] = n.Name
	n.fieldMap["description"] = n.Description
	n.fieldMap["deleted"] = n.Deleted
	n.fieldMap["created_at"] = n.CreatedAt
	n.fieldMap["updated_at"] = n.UpdatedAt
}

func (n njNamespace) clone(db *gorm.DB) njNamespace {
	n.njNamespaceDo.ReplaceConnPool(db.Statement.ConnPool)
	return n
}

func (n njNamespace) replaceDB(db *gorm.DB) njNamespace {
	n.njNamespaceDo.ReplaceDB(db)
	return n
}

type njNamespaceDo struct{ gen.DO }

type INjNamespaceDo interface {
	gen.SubQuery
	Debug() INjNamespaceDo
	WithContext(ctx context.Context) INjNamespaceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() INjNamespaceDo
	WriteDB() INjNamespaceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) INjNamespaceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) INjNamespaceDo
	Not(conds ...gen.Condition) INjNamespaceDo
	Or(conds ...gen.Condition) INjNamespaceDo
	Select(conds ...field.Expr) INjNamespaceDo
	Where(conds ...gen.Condition) INjNamespaceDo
	Order(conds ...field.Expr) INjNamespaceDo
	Distinct(cols ...field.Expr) INjNamespaceDo
	Omit(cols ...field.Expr) INjNamespaceDo
	Join(table schema.Tabler, on ...field.Expr) INjNamespaceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) INjNamespaceDo
	RightJoin(table schema.Tabler, on ...field.Expr) INjNamespaceDo
	Group(cols ...field.Expr) INjNamespaceDo
	Having(conds ...gen.Condition) INjNamespaceDo
	Limit(limit int) INjNamespaceDo
	Offset(offset int) INjNamespaceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) INjNamespaceDo
	Unscoped() INjNamespaceDo
	Create(values ...*model.NjNamespace) error
	CreateInBatches(values []*model.NjNamespace, batchSize int) error
	Save(values ...*model.NjNamespace) error
	First() (*model.NjNamespace, error)
	Take() (*model.NjNamespace, error)
	Last() (*model.NjNamespace, error)
	Find() ([]*model.NjNamespace, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjNamespace, err error)
	FindInBatches(result *[]*model.NjNamespace, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.NjNamespace) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) INjNamespaceDo
	Assign(attrs ...field.AssignExpr) INjNamespaceDo
	Joins(fields ...field.RelationField) INjNamespaceDo
	Preload(fields ...field.RelationField) INjNamespaceDo
	FirstOrInit() (*model.NjNamespace, error)
	FirstOrCreate() (*model.NjNamespace, error)
	FindByPage(offset int, limit int) (result []*model.NjNamespace, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) INjNamespaceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (n njNamespaceDo) Debug() INjNamespaceDo {
	return n.withDO(n.DO.Debug())
}

func (n njNamespaceDo) WithContext(ctx context.Context) INjNamespaceDo {
	return n.withDO(n.DO.WithContext(ctx))
}

func (n njNamespaceDo) ReadDB() INjNamespaceDo {
	return n.Clauses(dbresolver.Read)
}

func (n njNamespaceDo) WriteDB() INjNamespaceDo {
	return n.Clauses(dbresolver.Write)
}

func (n njNamespaceDo) Session(config *gorm.Session) INjNamespaceDo {
	return n.withDO(n.DO.Session(config))
}

func (n njNamespaceDo) Clauses(conds ...clause.Expression) INjNamespaceDo {
	return n.withDO(n.DO.Clauses(conds...))
}

func (n njNamespaceDo) Returning(value interface{}, columns ...string) INjNamespaceDo {
	return n.withDO(n.DO.Returning(value, columns...))
}

func (n njNamespaceDo) Not(conds ...gen.Condition) INjNamespaceDo {
	return n.withDO(n.DO.Not(conds...))
}

func (n njNamespaceDo) Or(conds ...gen.Condition) INjNamespaceDo {
	return n.withDO(n.DO.Or(conds...))
}

func (n njNamespaceDo) Select(conds ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.Select(conds...))
}

func (n njNamespaceDo) Where(conds ...gen.Condition) INjNamespaceDo {
	return n.withDO(n.DO.Where(conds...))
}

func (n njNamespaceDo) Order(conds ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.Order(conds...))
}

func (n njNamespaceDo) Distinct(cols ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.Distinct(cols...))
}

func (n njNamespaceDo) Omit(cols ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.Omit(cols...))
}

func (n njNamespaceDo) Join(table schema.Tabler, on ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.Join(table, on...))
}

func (n njNamespaceDo) LeftJoin(table schema.Tabler, on ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.LeftJoin(table, on...))
}

func (n njNamespaceDo) RightJoin(table schema.Tabler, on ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.RightJoin(table, on...))
}

func (n njNamespaceDo) Group(cols ...field.Expr) INjNamespaceDo {
	return n.withDO(n.DO.Group(cols...))
}

func (n njNamespaceDo) Having(conds ...gen.Condition) INjNamespaceDo {
	return n.withDO(n.DO.Having(conds...))
}

func (n njNamespaceDo) Limit(limit int) INjNamespaceDo {
	return n.withDO(n.DO.Limit(limit))
}

func (n njNamespaceDo) Offset(offset int) INjNamespaceDo {
	return n.withDO(n.DO.Offset(offset))
}

func (n njNamespaceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) INjNamespaceDo {
	return n.withDO(n.DO.Scopes(funcs...))
}

func (n njNamespaceDo) Unscoped() INjNamespaceDo {
	return n.withDO(n.DO.Unscoped())
}

func (n njNamespaceDo) Create(values ...*model.NjNamespace) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Create(values)
}

func (n njNamespaceDo) CreateInBatches(values []*model.NjNamespace, batchSize int) error {
	return n.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (n njNamespaceDo) Save(values ...*model.NjNamespace) error {
	if len(values) == 0 {
		return nil
	}
	return n.DO.Save(values)
}

func (n njNamespaceDo) First() (*model.NjNamespace, error) {
	if result, err := n.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjNamespace), nil
	}
}

func (n njNamespaceDo) Take() (*model.NjNamespace, error) {
	if result, err := n.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjNamespace), nil
	}
}

func (n njNamespaceDo) Last() (*model.NjNamespace, error) {
	if result, err := n.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjNamespace), nil
	}
}

func (n njNamespaceDo) Find() ([]*model.NjNamespace, error) {
	result, err := n.DO.Find()
	return result.([]*model.NjNamespace), err
}

func (n njNamespaceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.NjNamespace, err error) {
	buf := make([]*model.NjNamespace, 0, batchSize)
	err = n.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (n njNamespaceDo) FindInBatches(result *[]*model.NjNamespace, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return n.DO.FindInBatches(result, batchSize, fc)
}

func (n njNamespaceDo) Attrs(attrs ...field.AssignExpr) INjNamespaceDo {
	return n.withDO(n.DO.Attrs(attrs...))
}

func (n njNamespaceDo) Assign(attrs ...field.AssignExpr) INjNamespaceDo {
	return n.withDO(n.DO.Assign(attrs...))
}

func (n njNamespaceDo) Joins(fields ...field.RelationField) INjNamespaceDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Joins(_f))
	}
	return &n
}

func (n njNamespaceDo) Preload(fields ...field.RelationField) INjNamespaceDo {
	for _, _f := range fields {
		n = *n.withDO(n.DO.Preload(_f))
	}
	return &n
}

func (n njNamespaceDo) FirstOrInit() (*model.NjNamespace, error) {
	if result, err := n.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjNamespace), nil
	}
}

func (n njNamespaceDo) FirstOrCreate() (*model.NjNamespace, error) {
	if result, err := n.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.NjNamespace), nil
	}
}

func (n njNamespaceDo) FindByPage(offset int, limit int) (result []*model.NjNamespace, count int64, err error) {
	result, err = n.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = n.Offset(-1).Limit(-1).Count()
	return
}

func (n njNamespaceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = n.Count()
	if err != nil {
		return
	}

	err = n.Offset(offset).Limit(limit).Scan(result)
	return
}

func (n njNamespaceDo) Scan(result interface{}) (err error) {
	return n.DO.Scan(result)
}

func (n njNamespaceDo) Delete(models ...*model.NjNamespace) (result gen.ResultInfo, err error) {
	return n.DO.Delete(models)
}

func (n *njNamespaceDo) withDO(do gen.Dao) *njNamespaceDo {
	n.DO = *do.(*gen.DO)
	return n
}
