spring.application.name=natsjob-demo
#########################
# natsjob 配置
natsjob.enabled=true
natsjob.namespace=app
#注意如果配置密码中包含@等特殊字符需要进行转义，否则会报错
natsjob.nats-url=nats://127.0.0.1:4222
#########################
